---
title: "DSC640T302_Assignment2.2_LincolnBrown"
assignment: Assignment 2.2
output: html_notebook
author: Lincoln Brown
class: DSC640-T302
professor: Professor Williams
---
## Import Libraries

```{r}
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(readxl)
library(reshape2)
library(treemap)
```

### Import the expenditures dataframe
```{r}
expenditures_df <- read_excel("./ex2-2/expenditures.xlsx")
head(expenditures_df)
```
### Import the top 3 expenditures dataset
```{r}
top_expenditures_df <- read.csv("top_expenditures.csv")
head(top_expenditures_df)
```

### Load the World Population dataset
```{r}
world_pop_df <- read_excel('./ex2-2/world-population.xlsm')
head(world_pop_df)
```
### Load the Unemployment dataset
```{r}
unemployment_df <- read.csv('./ex2-2/unemployement-rate-1948-2010.csv')
head(unemployment_df)

```
## Tree Map
```{r}
# Create the labels and sizes
labels <- unique(top_expenditures_df$category)
sizes <- top_expenditures_df %>%
  group_by(category) %>%
  summarize(expenditure = sum(expenditure))

# Create the colors
colors <- c('#115d8e', '#fd6800', '#ab3414')

# Plot a tree map
treemap(
  sizes,
  index = 'category',
  vSize = 'expenditure',
  vColor = 'category',
  palette = colors,
  title = 'Tree Map of Top 3 Expense Categories for 84-08',
  fontsize.title = 15,
  fontsize.labels = 12,
  border.col = 'white',
  type = 'index'
)
```
## Area Chart
```{r}
# Create the area chart

ggplot(world_pop_df, aes(x = Year, y=Population)) +
  geom_area(fill = 'skyblue', alpha = 0.4) +
  geom_line(color = 'slateblue', size = 1) +
  scale_y_continuous(labels = function(x) paste0(x /1e6, "M")) +
  labs(
    title = 'Area Chart of World Population',
    x = 'Year',
    y = 'Population in Millions'
  ) + 
  theme_minimal()
```
## Stacked Area Chart
```{r}

ggplot(top_expenditures_df, aes(x = year, y = expenditure, fill = category)) +
  geom_area(alpha = 0.8) +
  scale_fill_manual(values = c('#fb9498', '#ffb773', '#8cafcd')) +
  scale_y_continuous(labels = scales::dollar_format(prefix = '$', suffix = 'M', scale = 1e-6)) +
  scale_x_continuous(breaks = seq(min(top_expenditures_df$year), max(top_expenditures_df$year), by = 2)) +
  labs(
    title = 'Stacked Area Chart of Top Expenditures 1984-2008',
    x = 'Year',
    y = 'Expense amount in USD',
    fill = 'Category'
  ) + 
  theme_minimal()
```
## Step Chart 
```{r}
# Get the yearly unemployment rates
yearly_values <- unemployment_df %>%
  group_by(Year) %>%
  summarize(Value = sum(Value))

# Create a step chart 
ggplot(yearly_values, aes(x = Year, y = Value)) +
  geom_step(color = 'blue') +
  labs(
    title = 'Step Chart of Unemployment Rate 1948-2010',
    x = 'Year',
    y = 'Unemployment Rate %'
  ) +
  theme_minimal() 
```

