---
title: "DSC640T302_Assignment2.2_LincolnBrown"
assignment: Assignment 2.2
output: html_notebook
author: Lincoln Brown
class: DSC640-T302
professor: Professor Williams
---
## Import Libraries
```{r}
library(dplyr)
library(ggplot2)
library(readxl)
library(scales)
```

## Import datasets
```{r}
top_crimes_df <- read_excel('./ex4-2/crimerates-by-state-2005_edit.xlsx', sheet = 'Sheet 3')
head(top_crimes_df, 10)

```


## Scatterplot of Top Ten States Murder Rate
```{r}
# Convert population to millions
top_crimes_df$population_millions <- top_crimes_df$population / 1e6
ggplot(top_crimes_df, aes(x = murder, y = population_millions, color = state)) +
  geom_point(size = 3, shape = 21, fill = NA, stroke = 1.5) + 
  ggtitle('Scatterplot of Top Ten States Murder Rates by Population') +
  xlab('Murder Rate') +
  ylab('Population') +
  scale_y_continuous(labels = number_format(scale = 1, suffix = 'M'),
                     breaks = seq(0, max(top_crimes_df$population_millions + 1)))
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  theme(legend.position = 'right')
```
## Bubble graph of Population vs Rape Rates: Bubble Size Indicates Murder Rate
```{r}
options(repr.plot.width=15, repr.plot.height=8)
# Create a bubble plot
ggplot(top_crimes_df, aes(x = population_millions, 
                          y = forcible_rape, size = murder, 
                          color = state)) +
  geom_point(shape = 21, fill = NA, stroke = 1.5) +
  ggtitle('Bubble Graph of Population vs Rape Rates: Bubble Size Indicates Murder Rate') +
  xlab('Population in Millions') + 
  ylab('Forcible Rape Rate') + 
  scale_size(range = c(3,10)) + 
  theme_minimal() + 
  scale_x_continuous(labels = number_format(scale = 1, suffix = 'M'),
                     breaks = seq(0, max(top_crimes_df$population_millions + 1))) +
  theme(legend.key.size = unit(.5,'line'))
```
## Density Plot of Population
```{r}
ggplot(top_crimes_df, aes(x = population_millions)) + 
  geom_density(fill = 'skyblue', alpha = 0.5, adjust = 1) +
  ggtitle('Density Plot of Population') + 
  xlab('Population in Millions') + 
  ylab('Density') +
  scale_x_continuous(limits = c(-2, 10)) +
  theme_minimal()
```

